version: '3.8'

services:
  database:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: blueocean
      POSTGRES_PASSWORD: docker
    ports:
      - 5431:5432
    volumes:
      - pg-data:/var/lib/postgresql/data
      - ./database/migration.sql:/docker-entrypoint-initdb.d/migration.sql

  app:
    image: admissions-hub-app
    build: .
    restart: always
    environment:
      CONNECTION_STRING: postgresql://postgres:docker@database/blueocean
    depends_on:
      - database
    ports:
      - 3000:3000
    volumes:
      - .:/app
    command: npm run dev

volumes:
  pg-data:
